"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Optional


class BaseSDK:
    def __init__(self, sdk_config, parent_ref: Optional[object] = None) -> None:
        self.sdk_configuration = sdk_config
        self.parent_ref = parent_ref

    def _get_url(self, base_url, url_variables):
        if base_url is not None:
            return base_url
        return self.sdk_configuration.get_server_details()[0]
