"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Optional

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration
from mistralai.client.conversations import Conversations


class Beta(BaseSDK):
    conversations: Conversations
    r"""(beta) Conversations API"""

    def __init__(
        self, sdk_config: SDKConfiguration, parent_ref: Optional[object] = None
    ) -> None:
        BaseSDK.__init__(self, sdk_config, parent_ref=parent_ref)
        self.sdk_configuration = sdk_config
        self._init_sdks()

    def _init_sdks(self):
        self.conversations = Conversations(
            self.sdk_configuration, parent_ref=self.parent_ref
        )
