"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, Mapping, Optional

from .basesdk import BaseSDK
from mistralai.client import models, utils
from mistralai.client._hooks import HookContext


class Embeddings(BaseSDK):
    r"""Embeddings API."""

    def create(
        self,
        *,
        model: str,
        inputs,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Any:
        r"""Embeddings"""
        base_url = None
        url_variables = None
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.EmbeddingRequest(model=model, inputs=inputs)

        req = self._build_request(
            method="POST",
            path="/v1/embeddings",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        )

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="embeddings_v1_embeddings_post",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
        )
        return utils.unmarshal_json_response(models.EmbeddingResponse, http_res)

    async def create_async(
        self,
        *,
        model: str,
        inputs,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Any:
        r"""Embeddings"""
        base_url = None
        url_variables = None
        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.EmbeddingRequest(model=model, inputs=inputs)

        req = self._build_request_async(
            method="POST",
            path="/v1/embeddings",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            timeout_ms=timeout_ms,
        )

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="embeddings_v1_embeddings_post",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
        )
        return utils.unmarshal_json_response(models.EmbeddingResponse, http_res)
