"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib
from typing import Optional, TYPE_CHECKING

from .basesdk import BaseSDK
from .sdkconfiguration import SDKConfiguration

if TYPE_CHECKING:
    from mistralai.client.beta import Beta
    from mistralai.client.chat import Chat
    from mistralai.client.embeddings import Embeddings
    from mistralai.client.models_ import Models
    from mistralai.client.ocr import Ocr


class Mistral(BaseSDK):
    r"""Mistral AI API: Our Chat Completion and Embeddings APIs specification."""

    chat: "Chat"
    r"""Chat Completion API."""
    embeddings: "Embeddings"
    r"""Embeddings API."""
    models: "Models"
    r"""Model Management API"""
    beta: "Beta"
    ocr: "Ocr"
    r"""OCR API"""
    _sub_sdk_map = {
        "chat": ("mistralai.client.chat", "Chat"),
        "embeddings": ("mistralai.client.embeddings", "Embeddings"),
        "models": ("mistralai.client.models_", "Models"),
        "beta": ("mistralai.client.beta", "Beta"),
        "ocr": ("mistralai.client.ocr", "Ocr"),
    }

    def __init__(
        self,
        api_key: Optional[str] = None,
        server_url: Optional[str] = None,
        client=None,
    ) -> None:
        BaseSDK.__init__(
            self,
            SDKConfiguration(client=client, security=api_key, server_url=server_url),
            parent_ref=self,
        )

    def dynamic_import(self, modname, retries=3):
        return importlib.import_module(modname)

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            module = self.dynamic_import(module_path)
            klass = getattr(module, class_name)
            instance = klass(self.sdk_configuration, parent_ref=self)
            setattr(self, name, instance)
            return instance
        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )
